### PR TITLE
V. 1.12 candidate files for MT4 and MT5

### PR DESCRIPTION
**Pull request by EarnForex**
Added 'rays until intersection' option.
Fixed TPO display issues when instrument's TickSize is higher than _Point.

### CODE REVIEW

**Comment by Heart1010** [comment]
the *rays are only shown correct when set 
```
ShowValueAreaRays = All
ShowMedianRays= All
RaysUntilIntersection = TRUE
```
image


**Otherwise strange things happens...**

e.g. 
image

or 
image

**Comment by EarnForex** [comment]
@Heart1010 Thanks for reporting on this! I have uploaded fixed files to this pull-request. The changes completely revise how the rays are applied to medians and value areas. Please test it and let me know how it works for you.

**Comment by Heart1010** [comment]
Regarding the rays... it looks better now 👍 - i only found one "problem"

1) when using ShowMedianRays = "previous & current" the median ray line from previous day is missing / same problem with ShowValueAreaRays when set to "previous & current". With all other options for the rays it's looking good!
image

But it happened again - the "missing" rectangles problem. I described it in the forum a while back but this time it was directly after opening the indicator settings, changed a ray setting and clicked ok. Right after that I had this

image

- here there are no "overlapping rectangles" but totally missing rectangles (I used first time the gradiend color settings so don't know how long this problem is there already)
image

And I normally use a line graph chart and set line graph color to NONE (so I only see the market profile) - but every x ticks the line graph "blinks in". Is this something caused by the indicator or is this a mt4 bug/problem?

image

---
settings used for screenshot above (or "missing rectangles" problem below)
```
Session=3
StartFromDate=1531699200
StartFromCurrentSession=true
SessionsToCount=15
ColorScheme=6
SaturdaySunday=0
SingleColor=6908265
MedianColor=17919
ValueAreaColor=4210752
ShowValueAreaRays=3
ShowMedianRays=3
RaysUntilIntersection=true
TimeShiftMinutes=0
PointMultiplier=20
ThrottleRedraw=6
EnableIntradaySession1=true
IntradaySession1StartTime=09:00
IntradaySession1EndTime=23:00
IntradaySession1ColorScheme=2
EnableIntradaySession2=false
IntradaySession2StartTime=09:00
IntradaySession2EndTime=23:00
IntradaySession2ColorScheme=6
EnableIntradaySession3=false
IntradaySession3StartTime=12:00
IntradaySession3EndTime=18:00
IntradaySession3ColorScheme=2
EnableIntradaySession4=false
IntradaySession4StartTime=18:00
IntradaySession4EndTime=00:00
IntradaySession4ColorScheme=3
```

**Comment by EarnForex** [comment]
I have found the source of the problem for rays not showing with PreviousCurrent.

What timeframe and trading instrument do you use in the screenshot for the rectangles problem? Also what's your trading server's timezone?

As for the blinking issue, it is an MT4 bug. I had reported it to MetaQuotes, but they replied that they do not plan to fix it in MT4.

**Comment by Heart1010** [comment]
M15, Symbol DAX30 (CFD, 1 digit, Broker GKFX)
Tradingserver timezone is UTC+2 (so in germany we have UTC+1, e. g. german 9:00 is shown as chart time 10:00)

**Comment by EarnForex** [comment]
I don't know, it looks very much OK from my side. Here is a screenshot from GKFX DAX30 @ M15 with your settings:
DAX30M15
Perhaps, it has something to do with the first issue (rays). I will now update the pull-request with the new files for you to try again.

**Comment by EarnForex** [comment]
If the issue with the rectangles persists, please save the indicator settings you use to a .set file and upload it here. Thanks!

**Comment by Heart1010** [comment]
I got this "missing rectangles" problem only one time.... it works 99% of the time until now. 
I will download and test further with your latest upload tommorrow 👍 
Thanks!

**Comment by ABACHOPPA** [comment]
Hi both,
Since the latest MT5 build update I too have been having intermittent rectangle disappearance issues, seems to be when the market makes a fast new high or low of the day from what I can figure out.
A simple refresh or time frame change fixes it so not a big issue as such. I'm wondering if there could be a small code update needed or a conflict of some sort in the latest Metatrader builds? Only thing I can think of.

**Pull request merged**
